// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlRTSgjL2GbRFE-I4bmyaCqeogSRPrqGQ',
    appId: '1:511714298489:web:88c4fe11d66a5e10c6e2a8',
    messagingSenderId: '511714298489',
    projectId: 'xavlogchat',
    authDomain: 'xavlogchat.firebaseapp.com',
    storageBucket: 'xavlogchat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRhu09Mc1K_R-i-uBriPr_JPIq-cGnzI',
    appId: '1:511714298489:android:911fe62eff54df9bc6e2a8',
    messagingSenderId: '511714298489',
    projectId: 'xavlogchat',
    storageBucket: 'xavlogchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ7tAmO3rsItMdsBm3yHAYGuNhSCl08Ks',
    appId: '1:511714298489:ios:cefeefafcf934169c6e2a8',
    messagingSenderId: '511714298489',
    projectId: 'xavlogchat',
    storageBucket: 'xavlogchat.firebasestorage.app',
    iosBundleId: 'com.example.xavlogMarketPlace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ7tAmO3rsItMdsBm3yHAYGuNhSCl08Ks',
    appId: '1:511714298489:ios:cefeefafcf934169c6e2a8',
    messagingSenderId: '511714298489',
    projectId: 'xavlogchat',
    storageBucket: 'xavlogchat.firebasestorage.app',
    iosBundleId: 'com.example.xavlogMarketPlace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlRTSgjL2GbRFE-I4bmyaCqeogSRPrqGQ',
    appId: '1:511714298489:web:332576f12855321dc6e2a8',
    messagingSenderId: '511714298489',
    projectId: 'xavlogchat',
    authDomain: 'xavlogchat.firebaseapp.com',
    storageBucket: 'xavlogchat.firebasestorage.app',
  );
}
