import 'package:flutter/material.dart';

class Product {
  final String image, title, description, condition, category;
  final int price, id;
  final Color color;

  Product({
    required this.id,
    required this.image,
    required this.title,
    required this.price,
    required this.description,
    required this.condition,
    required this.color,
    required this.category,
  });
}

List<Product> products = [
  Product(
      id: 1,
      title: "Cost Accounting Book",
      price: 10000,
      condition: "Like New",
      description: "Almost new, no damage.",
      image: "assets/images/item_1.png",
      color: const Color(0xFFB0BEC5),
      category: "Books"),
  Product(
      id: 2,
      title: "C++ Book",
      price: 234,
      condition: "Used",
      description: "A comprehensive guide to C++ programming.",
      image: "assets/images/item_2.png",
      color: const Color(0xFFA1887F),
      category: "Books"),
  Product(
      id: 3,
      title: "Foundation of Nursing",
      price: 234,
      condition: "Used",
      description: "Noticeable wear but fully functional.",
      image: "assets/images/item_3.png",
      color: const Color(0xFF8D6E63),
      category: "Books"),
  Product(
      id: 4,
      title: "Basketball",
      price: 500,
      condition: "New",
      description:
          "Official size and weight basketball, only used once in PE class.",
      image: "assets/images/item_14.png",
      color: const Color(0xFF757575),
      category: "PE Equipment"),
  Product(
      id: 5,
      title: "Lebron 19",
      price: 1500,
      condition: "Used",
      description: "Damaged sole",
      image: "assets/images/item_13.png",
      color: const Color(0xFF546E7A),
      category: "PE Equipment"),
  Product(
    id: 6,
    title: "Flutter for Dummies",
    price: 234,
    condition: "Sold for Repair",
    description: "Not functional, for parts or repair only.",
    image: "assets/images/item_6.png",
    color: const Color(0xFF37474F),
    category: "Books",
  ),
  Product(
    id: 9,
    title: "Smartwatch",
    price: 1200,
    condition: "Like New",
    description: "No scratches, fully functional.",
    image: "assets/images/item_7.png",
    color: const Color(0xFFB0BEC5),
    category: "Accessories",
  ),
  Product(
    id: 10,
    title: "Echo Dot",
    price: 2200,
    condition: "Used",
    description: "Buttons are fading, but still works.",
    image: "assets/images/item_8.png",
    color: const Color.fromARGB(255, 140, 196, 184),
    category: "Tech",
  ),
  Product(
    id: 11,
    title: "Luka's Shirt",
    price: 890,
    condition: "Used",
    description: "Selling because the size is too large.",
    image: "assets/images/item_9.png",
    color: const Color.fromARGB(255, 140, 47, 247),
    category: "Shirt",
  ),
  Product(
    id: 12,
    title: "HS PE Shirt",
    price: 140,
    condition: "Used",
    description: "Good and confortable.",
    image: "assets/images/item_10.png",
    color: const Color(0xFFB0BEC5),
    category: "PE Equipment",
  ),
  Product(
    id: 13,
    title: "Volleyball",
    price: 200,
    condition: "Used",
    description: "Bouncy good for training.",
    image: "assets/images/item_11.png",
    color: const Color(0xFFB0BEC5),
    category: "PE Equipment",
  ),
  Product(
    id: 14,
    title: "Yantok",
    price: 150,
    condition: "Used",
    description:
        "SSR Quality Yantok good for injuring bad guys, with demonic lifesteal enchantment",
    image: "assets/images/item_12.png",
    color: const Color(0xFFB0BEC5),
    category: "PE Equipment",
  ),
  Product(
    id: 13,
    title: "Aquaflask",
    price: 200,
    condition: "Used",
    description: "Small dent but usable",
    image: "assets/images/item_15.png",
    color: const Color(0xFFB0BEC5),
    category: "Others",
  ),
  Product(
    id: 14,
    title: "Siamese",
    price: 5000,
    condition: "Kitten",
    description: "Affectionate but deadly",
    image: "assets/images/item_16.png",
    color: const Color(0xFFB0BEC5),
    category: "Others",
  ),
  Product(
    id: 15,
    title: "Mechanical Mouse",
    price: 100,
    condition: "Used",
    description: "No battery",
    image: "assets/images/item_17.png",
    color: const Color(0xFFB0BEC5),
    category: "Tech",
  ),
];
